// Generated by simulator-core/backend/scripts/sync_stat_definitions.py.
// Do not edit manually; update the active theme stat_definitions.json.

export interface StatDefinitionMeta {
  id: string
  label: string
  icon: string
  default: number
  min: number
  max: number
  positiveEndpoint: 'max' | 'min' | 'none'
  allocatable: boolean
  allowItemEffect: boolean
  allowEventEffect: boolean
  llmContext: boolean
  showInCharacterCreate: boolean
  showInHud: boolean
}

export const STAT_INITIAL_BUDGET = 300

export const STAT_DEFINITIONS = [
  {
    "id": "energy",
    "label": "精力",
    "icon": "⚡",
    "default": 100,
    "min": 0,
    "max": 200,
    "positiveEndpoint": "max",
    "allocatable": false,
    "allowItemEffect": true,
    "allowEventEffect": true,
    "llmContext": true,
    "showInCharacterCreate": false,
    "showInHud": true
  },
  {
    "id": "sanity",
    "label": "心态",
    "icon": "💖",
    "default": 80,
    "min": 0,
    "max": 200,
    "positiveEndpoint": "max",
    "allocatable": false,
    "allowItemEffect": true,
    "allowEventEffect": true,
    "llmContext": true,
    "showInCharacterCreate": false,
    "showInHud": true
  },
  {
    "id": "stress",
    "label": "压力",
    "icon": "😰",
    "default": 0,
    "min": 0,
    "max": 200,
    "positiveEndpoint": "min",
    "allocatable": false,
    "allowItemEffect": true,
    "allowEventEffect": true,
    "llmContext": true,
    "showInCharacterCreate": false,
    "showInHud": true
  },
  {
    "id": "iq",
    "label": "IQ",
    "icon": "🧠",
    "default": 100,
    "min": 50,
    "max": 150,
    "positiveEndpoint": "max",
    "allocatable": true,
    "allowItemEffect": true,
    "allowEventEffect": false,
    "llmContext": true,
    "showInCharacterCreate": true,
    "showInHud": true
  },
  {
    "id": "eq",
    "label": "EQ",
    "icon": "💬",
    "default": 100,
    "min": 50,
    "max": 150,
    "positiveEndpoint": "max",
    "allocatable": true,
    "allowItemEffect": true,
    "allowEventEffect": true,
    "llmContext": true,
    "showInCharacterCreate": true,
    "showInHud": true
  },
  {
    "id": "luck",
    "label": "运气",
    "icon": "🍀",
    "default": 50,
    "min": 50,
    "max": 150,
    "positiveEndpoint": "max",
    "allocatable": true,
    "allowItemEffect": true,
    "allowEventEffect": true,
    "llmContext": true,
    "showInCharacterCreate": true,
    "showInHud": true
  },
  {
    "id": "charm",
    "label": "魅力",
    "icon": "✨",
    "default": 50,
    "min": 50,
    "max": 150,
    "positiveEndpoint": "max",
    "allocatable": true,
    "allowItemEffect": true,
    "allowEventEffect": true,
    "llmContext": true,
    "showInCharacterCreate": true,
    "showInHud": true
  },
  {
    "id": "reputation",
    "label": "声望",
    "icon": "🏛️",
    "default": 0,
    "min": 0,
    "max": 200,
    "positiveEndpoint": "max",
    "allocatable": false,
    "allowItemEffect": true,
    "allowEventEffect": true,
    "llmContext": true,
    "showInCharacterCreate": false,
    "showInHud": false
  },
  {
    "id": "efficiency",
    "label": "效率",
    "icon": "📈",
    "default": 100,
    "min": 0,
    "max": 300,
    "positiveEndpoint": "max",
    "allocatable": false,
    "allowItemEffect": true,
    "allowEventEffect": false,
    "llmContext": false,
    "showInCharacterCreate": false,
    "showInHud": false
  },
  {
    "id": "gold",
    "label": "金币",
    "icon": "💰",
    "default": 0,
    "min": 0,
    "max": 999999,
    "positiveEndpoint": "max",
    "allocatable": false,
    "allowItemEffect": false,
    "allowEventEffect": true,
    "llmContext": true,
    "showInCharacterCreate": false,
    "showInHud": true
  }
] as const satisfies readonly StatDefinitionMeta[]

export const ALLOCATABLE_STATS = STAT_DEFINITIONS.filter(
  (stat) => stat.allocatable,
)

export const STAT_META_BY_ID = Object.fromEntries(
  STAT_DEFINITIONS.map((stat) => [stat.id, stat]),
) as Record<string, StatDefinitionMeta>
