// Generated by simulator-core/backend/scripts/sync_theme_metadata.py.
// Do not edit manually; update themes/<theme_id>/theme.json.

export const THEME_MANIFEST = {
  "themeId": "zju",
  "displayName": "ZJUers Simulator",
  "locale": "zh-CN",
  "terms": {
    "institution": "折姜大学",
    "institution_short": "折大",
    "campus": "求是园",
    "feed": "求是园动态",
    "forum": "CC98",
    "messenger": "钉钉",
    "server": "折大服务器",
    "player": "同学",
    "player_nickname": "折大人",
    "semester": "学期",
    "course": "课程",
    "item": "道具",
    "rules": "折大校规",
    "notice": "折姜大学招生减章"
  },
  "storage": {
    "prefix": "simlab_zju"
  },
  "assets": {
    "hero": "assets/hero.webp",
    "logo": "assets/logo.webp"
  }
} as const

export type ThemeTermKey = keyof typeof THEME_MANIFEST.terms
