"""Installed theme-authoring and project-diagnostics helpers for esimu."""

from __future__ import annotations

import json
import os
from pathlib import Path
import re
import shutil
import sys
import tempfile
from typing import Any, Mapping

from esimu_core import PROTOCOL_VERSION, STATE_VERSION, THEME_SCHEMA_VERSION, __version__
from esimu_core.world.catalog import WorldCatalog
from esimu_core.world.prompts import PromptConfig
from esimu_core.world.stat_definitions import StatDefinitions
from esimu_core.world.story import ThemeStory
from esimu_core.world.theme import ThemeManifest
from esimu_core.world.theme_contract import validate_theme_pack
from esimu_core.world.theme_paths import DEFAULT_THEME_ID


def configure_project(root: str | Path, theme_id: str) -> tuple[Path, Path]:
    """Set the active project environment and return project/theme paths."""
    project = Path(root).expanduser().resolve()
    clean_theme = str(theme_id or DEFAULT_THEME_ID).strip() or DEFAULT_THEME_ID
    os.environ["ESIMU_PROJECT_ROOT"] = str(project)
    os.environ["ESIMU_THEME"] = clean_theme
    return project, project / "themes" / clean_theme


def metadata_documents(root: str | Path, theme_id: str) -> dict[Path, str]:
    """Render all frontend generated metadata for one explicit theme."""
    project, theme = configure_project(root, theme_id)
    manifest = ThemeManifest(theme / "theme.json")
    story = ThemeStory(theme / "story.json")
    stats = StatDefinitions(theme / "world" / "stat_definitions.json")
    output = project / "apps" / "starter" / "frontend" / "src" / "data"
    theme_json = json.dumps(manifest.public_metadata(), ensure_ascii=False, indent=2)
    story_json = json.dumps(story.public_metadata(), ensure_ascii=False, indent=2)
    stats_json = json.dumps(
        stats.public_metadata()["stats"], ensure_ascii=False, indent=2
    )
    return {
        output / "theme.generated.ts": (
            "// Generated by esimu sync.\n"
            "// Do not edit manually; update themes/<theme_id>/theme.json.\n\n"
            f"export const THEME_MANIFEST = {theme_json} as const\n\n"
            "export type ThemeTermKey = keyof typeof THEME_MANIFEST.terms\n"
        ),
        output / "story.generated.ts": (
            "// Generated by esimu sync.\n"
            "// Do not edit manually; update themes/<theme_id>/story.json.\n\n"
            f"export const STORY_CONTENT = {story_json} as const\n\n"
            "export type PrologueTone = "
            "typeof STORY_CONTENT.prologue.scenes[number]['tone']\n"
        ),
        output / "statDefinitions.generated.ts": (
            "// Generated by esimu sync.\n"
            "// Do not edit manually; update the active theme stat_definitions.json.\n\n"
            "export interface StatDefinitionMeta {\n"
            "  id: string\n  label: string\n  icon: string\n  default: number\n"
            "  min: number\n  max: number\n"
            "  positiveEndpoint: 'max' | 'min' | 'none'\n"
            "  allocatable: boolean\n  allowItemEffect: boolean\n"
            "  allowEventEffect: boolean\n  llmContext: boolean\n"
            "  showInCharacterCreate: boolean\n  showInHud: boolean\n}\n\n"
            f"export const STAT_INITIAL_BUDGET = {stats.initial_budget}\n\n"
            "export const STAT_DEFINITIONS = "
            f"{stats_json} as const satisfies readonly StatDefinitionMeta[]\n\n"
            "export const ALLOCATABLE_STATS = STAT_DEFINITIONS.filter(\n"
            "  (stat) => stat.allocatable,\n)\n\n"
            "export const STAT_META_BY_ID = Object.fromEntries(\n"
            "  STAT_DEFINITIONS.map((stat) => [stat.id, stat]),\n"
            ") as Record<string, StatDefinitionMeta>\n"
        ),
    }


def sync_project_metadata(
    root: str | Path,
    theme_id: str,
    *,
    write: bool,
) -> dict[str, Any]:
    """Check or atomically update all generated frontend metadata."""
    project, theme = configure_project(root, theme_id)
    documents = metadata_documents(project, theme_id)
    stale = [path for path, expected in documents.items() if _read(path) != expected]
    if write:
        issues = validate_theme_pack(theme)
        if issues:
            raise ValueError("theme validation failed before sync: " + "; ".join(
                issue.format() for issue in issues
            ))
        backups = {
            path: path.read_bytes() if path.exists() else None for path in documents
        }
        try:
            for path, expected in documents.items():
                _atomic_write(path, expected)
        except Exception:
            _restore_files(backups)
            raise
    return {
        "theme": theme_id,
        "mode": "write" if write else "check",
        "current": not stale,
        "files": [str(path.relative_to(project)) for path in documents],
        "stale": [str(path.relative_to(project)) for path in stale],
    }


def inspect_project(root: str | Path, theme_id: str) -> dict[str, Any]:
    """Return a stable public summary of one project and theme pack."""
    project, theme = configure_project(root, theme_id)
    catalog = WorldCatalog(theme_id, theme / "world")
    manifest = ThemeManifest(theme / "theme.json")
    stats = StatDefinitions(theme / "world" / "stat_definitions.json")
    items_raw = catalog.load_json(catalog.path("items.json"), {})
    characters = catalog.load_json(catalog.path("characters.json"), [])
    course_count = sum(
        len(catalog.courses_for_semester(str(major.get("abbr")), semester))
        for major in catalog.majors()
        for semester in range(1, 65)
    )
    metadata = metadata_documents(project, theme_id)
    return {
        "core_version": __version__,
        "contracts": {
            "theme": THEME_SCHEMA_VERSION,
            "state": STATE_VERSION,
            "protocol": PROTOCOL_VERSION,
        },
        "project_root": str(project),
        "theme": manifest.public_metadata(),
        "counts": {
            "majors": len(catalog.majors()),
            "courses": course_count,
            "stats": len(stats.stats),
            "items": len(items_raw.get("items", [])) if isinstance(items_raw, Mapping) else 0,
            "events": len(catalog.event_library()),
            "forum_posts": len(catalog.forum_library()),
            "characters": len(characters) if isinstance(characters, list) else 0,
            "achievements": len(catalog.achievements()),
        },
        "generated_outputs": [str(path) for path in metadata],
    }


def doctor_project(root: str | Path, theme_id: str) -> dict[str, Any]:
    """Run non-mutating project, contract, and toolchain diagnostics."""
    project, theme = configure_project(root, theme_id)
    checks: list[dict[str, str]] = []

    def add(name: str, status: str, detail: str) -> None:
        checks.append({"name": name, "status": status, "detail": detail})

    add(
        "python",
        "ok" if sys.version_info >= (3, 11) else "error",
        f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}",
    )
    add("esimu-core", "ok", __version__)
    issues = validate_theme_pack(theme)
    add(
        "theme",
        "ok" if not issues else "error",
        "valid" if not issues else "; ".join(issue.format() for issue in issues),
    )
    try:
        sync = sync_project_metadata(project, theme_id, write=False)
        add(
            "frontend-metadata",
            "ok" if sync["current"] else "error",
            "current" if sync["current"] else "stale: " + ", ".join(sync["stale"]),
        )
    except Exception as exc:
        add("frontend-metadata", "error", str(exc))

    backend = project / "apps" / "starter" / "backend" / "app" / "main.py"
    frontend = project / "apps" / "starter" / "frontend" / "package.json"
    add("starter-backend", "ok" if backend.is_file() else "error", str(backend))
    add("starter-frontend", "ok" if frontend.is_file() else "error", str(frontend))
    for executable in ("node", "corepack", "pnpm"):
        resolved = shutil.which(executable)
        status = "ok" if resolved else ("warning" if executable == "pnpm" else "error")
        add(executable, status, resolved or "not found on PATH")

    database = Path(
        os.environ.get(
            "ESIMU_STARTER_DATABASE_PATH",
            project / "data" / "esimu.sqlite3",
        )
    ).expanduser()
    parent = database.parent
    writable_parent = parent if parent.exists() else parent.parent
    add(
        "sqlite-path",
        "ok" if writable_parent.exists() and os.access(writable_parent, os.W_OK) else "warning",
        str(database.resolve()),
    )
    return {
        "ok": not any(check["status"] == "error" for check in checks),
        "theme": theme_id,
        "checks": checks,
        "ai": {
            "general_configured": bool(os.environ.get("ESIMU_LLM_API_KEY")),
            "roleplay_configured": bool(os.environ.get("ESIMU_RP_API_KEY")),
        },
    }


def add_world_entry(
    root: str | Path,
    theme_id: str,
    kind: str,
    entry_id: str,
    options: Mapping[str, Any],
    *,
    write: bool,
) -> dict[str, Any]:
    """Preview or atomically add one supported theme/world entry."""
    project, theme = configure_project(root, theme_id)
    clean_id = _identifier(entry_id)
    target, data, entry = _draft_entry(theme, kind, clean_id, options)
    if not write:
        return {"kind": kind, "id": clean_id, "write": False, "entry": entry}

    documents = metadata_documents(project, theme_id)
    protected = {target, *documents.keys()}
    backups = {path: path.read_bytes() if path.exists() else None for path in protected}
    try:
        _atomic_write(target, json.dumps(data, ensure_ascii=False, indent=2) + "\n")
        sync_project_metadata(project, theme_id, write=True)
        issues = validate_theme_pack(theme)
        if issues:
            raise ValueError("; ".join(issue.format() for issue in issues))
    except Exception:
        _restore_files(backups)
        raise
    return {
        "kind": kind,
        "id": clean_id,
        "write": True,
        "path": str(target.relative_to(project)),
        "entry": entry,
    }


def _draft_entry(
    theme: Path,
    kind: str,
    entry_id: str,
    options: Mapping[str, Any],
) -> tuple[Path, Any, dict[str, Any]]:
    world = theme / "world"
    name = str(options.get("name") or entry_id)
    if kind == "stat":
        target = world / "stat_definitions.json"
        data = _json(target, {})
        entries = data.get("stats") if isinstance(data, dict) else None
        if not isinstance(entries, list):
            raise ValueError("stat_definitions.json must contain a stats array")
        entry = {
            "id": entry_id,
            "label": str(options.get("label") or name),
            "icon": str(options.get("icon") or "✨"),
            "default": int(options.get("default", 0)),
            "min": int(options.get("minimum", 0)),
            "max": int(options.get("maximum", 200)),
            "positive_endpoint": str(options.get("positive_endpoint") or "max"),
            "allocatable": bool(options.get("allocatable", False)),
            "allow_item_effect": bool(options.get("allow_item_effect", False)),
            "allow_event_effect": bool(options.get("allow_event_effect", False)),
            "llm_context": bool(options.get("llm_context", False)),
            "show_in_character_create": bool(options.get("allocatable", False)),
            "show_in_hud": bool(options.get("show_in_hud", False)),
        }
        if entry["allocatable"] and options.get("adjust_budget"):
            data["initial_budget"] = int(data.get("initial_budget", 0)) + int(
                entry["default"]
            )
        _append_unique(entries, entry, "id")
        return target, data, entry
    if kind == "item":
        target = world / "items.json"
        data = _json(target, {})
        entries = data.get("items") if isinstance(data, dict) else None
        if not isinstance(entries, list):
            raise ValueError("items.json must contain an items array")
        effect = str(options.get("effect") or "energy")
        entry = {
            "id": entry_id,
            "name": name,
            "category": str(options.get("category") or "general"),
            "tags": _tags(options.get("tags")),
            "price": int(options.get("price", 50)),
            "description": str(options.get("description") or "Describe this item."),
            "effects": {effect: int(options.get("effect_value", 5))},
        }
        if options.get("sell_price") is not None:
            entry["sell_price"] = int(options["sell_price"])
        _append_unique(entries, entry, "id")
        return target, data, entry
    if kind == "achievement":
        target = world / "achievements.json"
        data = _json(target, [])
        if not isinstance(data, list):
            raise ValueError("achievements.json must contain an array")
        entry = {
            "code": entry_id,
            "name": name,
            "desc": str(options.get("description") or "Describe this achievement."),
            "icon": str(options.get("icon") or "🏅"),
            "condition": {
                "all": [
                    {
                        "scope": str(options.get("scope") or "action"),
                        "key": str(options.get("key") or "relax"),
                        "op": str(options.get("op") or "gte"),
                        "value": _scalar(options.get("value", 1)),
                    }
                ]
            },
        }
        _append_unique(data, entry, "code")
        return target, data, entry
    if kind == "event":
        target = world / "event_library.json"
        data = _json(target, [])
        if not isinstance(data, list):
            raise ValueError("event_library.json must contain an array")
        effect = str(options.get("effect") or "sanity")
        entry = {
            "id": entry_id,
            "title": str(options.get("title") or name),
            "description": str(options.get("description") or "A short event setup."),
            "options": [
                {
                    "text": str(options.get("option_text") or "Try it"),
                    "effects": {
                        effect: int(options.get("effect_value", 5)),
                        "desc": str(options.get("result") or "Describe what changed."),
                    },
                },
                {
                    "text": str(options.get("second_option_text") or "Leave it"),
                    "effects": {
                        "desc": str(
                            options.get("second_result") or "You let it pass."
                        )
                    },
                },
            ],
        }
        _append_unique(data, entry, "id")
        return target, data, entry
    if kind == "course":
        plan = str(options.get("plan") or "GEN")
        target = world / "courses" / f"{plan}.json"
        data = _json(target, [])
        semester = int(options.get("semester", 1))
        entry = {
            "id": entry_id,
            "name": name,
            "credits": float(options.get("credits", 3)),
            "difficulty": float(options.get("difficulty", 1)),
            "description": str(options.get("description") or "Course description."),
            "semester": semester,
        }
        if isinstance(data, list):
            _append_unique(data, entry, "id")
        elif isinstance(data, dict):
            terms = data.get("semesters") or data.get("plan")
            if not isinstance(terms, list):
                raise ValueError("course plan must contain semesters or plan array")
            term = next(
                (
                    item
                    for index, item in enumerate(terms)
                    if isinstance(item, dict)
                    and int(item.get("semester", index + 1) or index + 1) == semester
                ),
                None,
            )
            if term is None:
                term = {"semester": semester, "courses": []}
                terms.append(term)
            courses = term.get("courses")
            if not isinstance(courses, list):
                raise ValueError("course term must contain a courses array")
            _append_unique(courses, entry, "id")
        else:
            raise ValueError("course plan must contain an array or object")
        return target, data, entry
    if kind == "prompt":
        target = theme / "prompts.json"
        data = _json(target, {})
        if not isinstance(data, dict):
            raise ValueError("prompts.json must contain an object")
        if entry_id not in PromptConfig.model_fields:
            raise ValueError(f"unknown prompt field: {entry_id}")
        entry = {entry_id: str(options.get("text") or "Describe this prompt fragment.")}
        data.update(entry)
        return target, data, entry
    raise ValueError(f"unsupported entry kind: {kind}")


def _append_unique(entries: list[Any], entry: dict[str, Any], id_field: str) -> None:
    entry_id = entry[id_field]
    if any(isinstance(item, Mapping) and item.get(id_field) == entry_id for item in entries):
        raise ValueError(f"entry already exists: {entry_id}")
    entries.append(entry)


def _identifier(value: str) -> str:
    candidate = str(value).strip()
    if not re.fullmatch(r"[a-z][a-z0-9_]*", candidate):
        raise ValueError("id must match [a-z][a-z0-9_]*")
    return candidate


def _json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def _tags(value: Any) -> list[str]:
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    return [item.strip() for item in str(value or "general").split(",") if item.strip()]


def _scalar(value: Any) -> str | int | float | bool:
    if isinstance(value, str):
        lowered = value.strip().lower()
        if lowered in {"true", "false"}:
            return lowered == "true"
        try:
            return float(value) if "." in value else int(value)
        except ValueError:
            return value
    if isinstance(value, int | float | bool):
        return value
    return str(value)


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        os.replace(temp_name, path)
    except Exception:
        Path(temp_name).unlink(missing_ok=True)
        raise


def _restore_files(backups: Mapping[Path, bytes | None]) -> None:
    for path, content in backups.items():
        if content is None:
            path.unlink(missing_ok=True)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
