"""Bootstrap a new esimu-based simulator project.

The generator intentionally copies the small starter app and a theme pack, then
prints a checklist. It avoids rewriting reference-app internals so new projects
do not accidentally inherit ZJU-specific production history.
"""

from __future__ import annotations

import argparse
import atexit
import json
import re
import shutil
import tempfile
import zipfile
import sys
from importlib import resources
from pathlib import Path
from typing import Any

PACKAGE_ROOT = Path(__file__).resolve().parent
REPOSITORY_ROOT = PACKAGE_ROOT.parents[2]


from esimu_core import __version__ as ESIMU_CORE_VERSION  # noqa: E402

DEFAULT_CORE_DEPENDENCY = f"esimu-core[ai]=={ESIMU_CORE_VERSION}"

SKIP_DIR_NAMES = {
    ".git",
    ".pytest_cache",
    ".ruff_cache",
    "__pycache__",
    "node_modules",
    "dist",
    ".vite",
}
SKIP_SUFFIXES = {".pyc", ".pyo"}

_EXTRACTED_SOURCE_ROOT: Path | None = None


def _source_root() -> Path:
    """Return repository templates or extract the wheel-owned bundle."""
    global _EXTRACTED_SOURCE_ROOT
    if (REPOSITORY_ROOT / "apps" / "starter").is_dir():
        return REPOSITORY_ROOT
    if _EXTRACTED_SOURCE_ROOT is not None:
        return _EXTRACTED_SOURCE_ROOT

    resource = resources.files("esimu_core").joinpath(
        "scaffold", "esimu-starter.zip"
    )
    temp_root = Path(tempfile.mkdtemp(prefix="esimu-scaffold-"))
    with resources.as_file(resource) as archive:
        with zipfile.ZipFile(archive) as bundle:
            bundle.extractall(temp_root)
    _EXTRACTED_SOURCE_ROOT = temp_root
    atexit.register(shutil.rmtree, temp_root, True)
    return temp_root


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", value.strip().lower()).strip("-")
    return slug or "simulator"


def _storage_prefix(theme_id: str) -> str:
    return re.sub(r"[^a-z0-9_]+", "_", theme_id.replace("-", "_").lower()).strip("_")


def _read_json(path: Path) -> dict[str, Any]:
    with open(path, encoding="utf-8") as file:
        data = json.load(file)
    if not isinstance(data, dict):
        raise ValueError(f"{path} must be a JSON object")
    return data


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )


def _should_skip(path: Path) -> bool:
    return path.name in SKIP_DIR_NAMES or path.suffix in SKIP_SUFFIXES


def _copytree_filtered(source: Path, target: Path) -> None:
    for child in source.iterdir():
        if _should_skip(child):
            continue
        destination = target / child.name
        if child.is_dir():
            destination.mkdir(parents=True, exist_ok=True)
            _copytree_filtered(child, destination)
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(child, destination)


def _copy_story_assets(theme_root: Path, story: dict[str, Any]) -> None:
    theme_assets = theme_root / "assets"
    prologue = story.get("prologue") if isinstance(story.get("prologue"), dict) else {}
    endings = story.get("endings") if isinstance(story.get("endings"), dict) else {}
    scenes = prologue.get("scenes") if isinstance(prologue.get("scenes"), list) else []
    image_names = {
        str(scene.get("image"))
        for scene in scenes
        if isinstance(scene, dict) and scene.get("image")
    }
    image_names.update(
        str(name)
        for name in endings.get("graduation_background_images", [])
        if isinstance(name, str)
    )
    for image_name in sorted(image_names):
        source = theme_assets / image_name
        if source.exists():
            continue
        raise ValueError(f"story asset {image_name} is missing from {theme_assets}")


def _theme_typescript(theme: dict[str, Any]) -> str:
    metadata = {
        "schemaVersion": int(theme.get("schema_version", 1)),
        "themeId": str(theme.get("theme_id") or ""),
        "displayName": str(theme.get("display_name") or ""),
        "locale": str(theme.get("locale") or "zh-CN"),
        "terms": dict(theme.get("terms") or {}),
        "storage": dict(theme.get("storage") or {}),
        "assets": dict(theme.get("assets") or {}),
    }
    metadata_json = json.dumps(metadata, ensure_ascii=False, indent=2)
    return (
        "// Generated by esimu new.\n"
        "// Do not edit manually; update themes/<theme_id>/theme.json.\n\n"
        f"export const THEME_MANIFEST = {metadata_json} as const\n\n"
        "export type ThemeTermKey = keyof typeof THEME_MANIFEST.terms\n"
    )


def _story_typescript(story: dict[str, Any]) -> str:
    metadata_json = json.dumps(story, ensure_ascii=False, indent=2)
    return (
        "// Generated by esimu new.\n"
        "// Do not edit manually; update themes/<theme_id>/story.json.\n\n"
        f"export const STORY_CONTENT = {metadata_json} as const\n\n"
        "export type PrologueTone = "
        "typeof STORY_CONTENT.prologue.scenes[number]['tone']\n"
    )


def _stat_typescript(stat_definitions: dict[str, Any]) -> str:
    stats = stat_definitions.get("stats")
    if not isinstance(stats, list):
        raise ValueError("stat_definitions.json must contain a stats array")
    budget = int(stat_definitions.get("initial_budget", 0))
    metadata = []
    for stat in stats:
        if not isinstance(stat, dict):
            continue
        metadata.append(
            {
                "id": stat["id"],
                "label": stat["label"],
                "icon": stat["icon"],
                "default": stat["default"],
                "min": stat["min"],
                "max": stat["max"],
                "positiveEndpoint": stat["positive_endpoint"],
                "allocatable": stat["allocatable"],
                "allowItemEffect": stat["allow_item_effect"],
                "allowEventEffect": stat["allow_event_effect"],
                "llmContext": stat["llm_context"],
                "showInCharacterCreate": stat["show_in_character_create"],
                "showInHud": stat["show_in_hud"],
            }
        )
    metadata_json = json.dumps(metadata, ensure_ascii=False, indent=2)
    return (
        "// Generated by esimu new.\n"
        "// Do not edit manually; update the active theme stat_definitions.json.\n\n"
        "export interface StatDefinitionMeta {\n"
        "  id: string\n"
        "  label: string\n"
        "  icon: string\n"
        "  default: number\n"
        "  min: number\n"
        "  max: number\n"
        "  positiveEndpoint: 'max' | 'min' | 'none'\n"
        "  allocatable: boolean\n"
        "  allowItemEffect: boolean\n"
        "  allowEventEffect: boolean\n"
        "  llmContext: boolean\n"
        "  showInCharacterCreate: boolean\n"
        "  showInHud: boolean\n"
        "}\n\n"
        f"export const STAT_INITIAL_BUDGET = {budget}\n\n"
        "export const STAT_DEFINITIONS = "
        f"{metadata_json} as const satisfies readonly StatDefinitionMeta[]\n\n"
        "export const ALLOCATABLE_STATS = STAT_DEFINITIONS.filter(\n"
        "  (stat) => stat.allocatable,\n"
        ")\n\n"
        "export const STAT_META_BY_ID = Object.fromEntries(\n"
        "  STAT_DEFINITIONS.map((stat) => [stat.id, stat]),\n"
        ") as Record<string, StatDefinitionMeta>\n"
    )


def _patch_starter_files(target: Path, theme_id: str, core_dependency: str) -> None:
    session_path = target / "apps" / "starter" / "backend" / "app" / "session.py"
    session = session_path.read_text(encoding="utf-8")
    session = session.replace(
        'os.environ.setdefault("ESIMU_THEME", "demo-campus")',
        f'os.environ.setdefault("ESIMU_THEME", "{theme_id}")',
    )
    session = session.replace(
        'theme_id: str = "demo-campus"', f'theme_id: str = "{theme_id}"'
    )
    session_path.write_text(session, encoding="utf-8")

    bootstrap_path = target / "apps" / "starter" / "backend" / "app" / "bootstrap.py"
    bootstrap = bootstrap_path.read_text(encoding="utf-8")
    bootstrap = bootstrap.replace(
        'default_theme: str = "demo-campus"',
        f'default_theme: str = "{theme_id}"',
    )
    bootstrap_path.write_text(bootstrap, encoding="utf-8")

    backend_tests = (
        target / "apps" / "starter" / "backend" / "tests" / "test_starter_smoke.py"
    )
    test_text = backend_tests.read_text(encoding="utf-8")
    backend_tests.write_text(
        test_text.replace('"demo-campus"', f'"{theme_id}"'),
        encoding="utf-8",
    )
    requirements = target / "apps" / "starter" / "backend" / "requirements.txt"
    lines = requirements.read_text(encoding="utf-8").splitlines()
    updated = [core_dependency if line.startswith("-e ") else line for line in lines]
    requirements.write_text("\n".join(updated) + "\n", encoding="utf-8")

    package_json_path = target / "apps" / "starter" / "frontend" / "package.json"
    package_json = _read_json(package_json_path)
    package_json["name"] = f"{theme_id}-frontend"
    _write_json(package_json_path, package_json)


def _write_generated_frontend_data(target: Path, theme_id: str) -> None:
    data_dir = target / "apps" / "starter" / "frontend" / "src" / "data"
    theme_root = target / "themes" / theme_id
    data_dir.mkdir(parents=True, exist_ok=True)
    (data_dir / "theme.generated.ts").write_text(
        _theme_typescript(_read_json(theme_root / "theme.json")),
        encoding="utf-8",
    )
    (data_dir / "story.generated.ts").write_text(
        _story_typescript(_read_json(theme_root / "story.json")),
        encoding="utf-8",
    )
    (data_dir / "statDefinitions.generated.ts").write_text(
        _stat_typescript(_read_json(theme_root / "world" / "stat_definitions.json")),
        encoding="utf-8",
    )


def _write_project_docs(target: Path, args: argparse.Namespace) -> None:
    readme = f"""# {args.project_name}

This simulator was generated from esimu's starter app.

## Quick Start

```powershell
cd <project-directory>
python -m venv .venv
.\\.venv\\Scripts\\Activate.ps1
python -m pip install -r apps\\starter\\backend\\requirements.txt
esimu validate --root . --theme {args.theme_id}
cd apps\\starter\\backend
python -m uvicorn app.main:app --reload --port 18001
```

Frontend (in a second terminal):

```powershell
cd <project-directory>\\apps\\starter\\frontend
corepack pnpm install --frozen-lockfile
corepack pnpm dev
```

Open `http://127.0.0.1:15175`. Vite proxies `/api`, `/config`, `/healthz`, and
`/ws` to the starter backend. For split-origin deployment, copy
`apps/starter/frontend/.env.example` to `.env` and set the public API/WS bases.

## Theme

- Theme ID: `{args.theme_id}`
- Theme directory: `themes/{args.theme_id}/`
- Storage prefix: `{args.storage_prefix}`

Start by editing `themes/{args.theme_id}/theme.json`, `story.json`,
`prompts.json`, and files under `world/`.
"""
    (target / "README.md").write_text(readme, encoding="utf-8")
    (target / ".env.example").write_text(
        (
            f"ESIMU_THEME={args.theme_id}\n"
            "ESIMU_PROJECT_ROOT=.\n"
            "ESIMU_CORS_ORIGINS=http://127.0.0.1:15175,http://localhost:15175\n"
            "ESIMU_CONTENT_MODE=library\n"
            "ESIMU_HYBRID_AI_PROBABILITY=0.35\n"
            "ESIMU_LLM_PROVIDER=openai\n"
            "ESIMU_LLM_MODEL=gpt-4o-mini\n"
            "ESIMU_LLM_API_KEY=\n"
            "ESIMU_LLM_BASE_URL=\n"
            "ESIMU_RP_PROVIDER=minimax\n"
            "ESIMU_RP_MODEL=M2-her\n"
            "ESIMU_RP_API_KEY=\n"
            "ESIMU_RP_BASE_URL=https://api.minimaxi.com/v1\n"
        ),
        encoding="utf-8",
    )
    (target / ".gitignore").write_text(
        "\n".join(
            [
                ".env",
                ".venv/",
                "__pycache__/",
                "*.py[cod]",
                ".pytest_cache/",
                ".ruff_cache/",
                "node_modules/",
                "dist/",
                ".vite/",
                "data/",
                "logs/",
                "*.log",
                "",
            ]
        ),
        encoding="utf-8",
    )

    docs_dir = target / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    (docs_dir / "scaffold-checklist.md").write_text(
        f"""# Scaffold Checklist

Use this checklist before turning `{args.project_name}` into a real game.

## Theme Files

- `themes/{args.theme_id}/theme.json`: visible terms, storage prefix, assets.
- `themes/{args.theme_id}/story.json`: prologue and ending copy.
- `themes/{args.theme_id}/prompts.json`: model-facing context.
- `themes/{args.theme_id}/world/stat_definitions.json`: player stats.
- `themes/{args.theme_id}/world/items.json`: item catalog and economy.
- `themes/{args.theme_id}/world/majors.json`: roles or majors.
- `themes/{args.theme_id}/world/courses/*.json`: course/task plans.
- `themes/{args.theme_id}/world/event_library.json`: local events.
- `themes/{args.theme_id}/world/forum_library.json`: forum-style local posts.
- `themes/{args.theme_id}/world/achievements.json`: achievements.

## Useful esimu Commands

```powershell
cd <project-directory>
esimu validate --root . --theme {args.theme_id}
python scripts\\scaffold_game_stat.py add focus --label 专注 --show-in-hud
python scripts\\scaffold_world_data.py item focus_card --name 专注卡
python scripts\\scaffold_world_data.py achievement first_win --name 第一次胜利
python scripts\\scaffold_world_data.py event campus_moment --title 校园一刻
```
""",
        encoding="utf-8",
    )

def _write_agent_file(target: Path, args: argparse.Namespace) -> None:
    template = (_source_root() / "templates" / "agent" / "AGENTS.md").read_text(
        encoding="utf-8"
    )
    replacements = {
        "<project-name>": args.project_name,
        "<absolute-project-root>": ".",
        "<theme-id>": args.theme_id,
        "<backend-path>": "apps/starter/backend",
        "<frontend-path>": "apps/starter/frontend",
        "<theme-path>": f"themes/{args.theme_id}",
        "<python>": "python",
        "<validate-world-data-script>": (
            f"-m esimu_core.cli --root . --theme {args.theme_id}"
        ),
        "<backend-tests-path>": "apps/starter/backend/tests",
        "<backend-app-path>": "apps/starter/backend/app",
        "<compatibility-id-1>": "forum",
        "<compatibility-id-2>": "messenger",
    }
    for old, new in replacements.items():
        template = template.replace(old, new)
    (target / "AGENTS.md").write_text(template, encoding="utf-8")


def bootstrap_project(args: argparse.Namespace) -> Path:
    """Create a new project directory from the starter app and source theme."""
    target = args.target.expanduser().resolve()
    if target.exists() and any(target.iterdir()) and not args.force:
        raise ValueError(f"target already exists and is not empty: {target}")
    target.mkdir(parents=True, exist_ok=True)

    source_root = _source_root()
    starter_source = source_root / "apps" / "starter"
    theme_source = source_root / "themes" / args.source_theme
    if not starter_source.exists():
        raise ValueError(f"starter source not found: {starter_source}")
    if not theme_source.exists():
        raise ValueError(f"source theme not found: {theme_source}")

    _copytree_filtered(starter_source, target / "apps" / "starter")
    scripts_target = target / "scripts"
    scripts_target.mkdir(parents=True, exist_ok=True)
    for script_name in ("scaffold_game_stat.py", "scaffold_world_data.py"):
        shutil.copy2(
            source_root / "packages" / "esimu-core" / "scripts" / script_name,
            scripts_target / script_name,
        )
    theme_target = target / "themes" / args.theme_id
    _copytree_filtered(theme_source, theme_target)

    theme = _read_json(theme_target / "theme.json")
    theme["theme_id"] = args.theme_id
    theme["display_name"] = args.display_name
    theme.setdefault("storage", {})["prefix"] = args.storage_prefix
    terms = theme.setdefault("terms", {})
    terms["institution"] = args.institution
    terms["institution_short"] = args.institution_short
    terms["campus"] = args.institution
    terms["forum"] = args.forum_name
    terms["messenger"] = args.messenger_name
    _write_json(theme_target / "theme.json", theme)

    story = _read_json(theme_target / "story.json")
    _copy_story_assets(theme_target, story)
    _patch_starter_files(target, args.theme_id, args.core_dependency)
    _write_generated_frontend_data(target, args.theme_id)
    _write_project_docs(target, args)
    _write_agent_file(target, args)
    return target


def build_parser() -> argparse.ArgumentParser:
    """Build the CLI parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("target", type=Path, help="directory to create")
    parser.add_argument(
        "--project-name", default="", help="human-readable project name"
    )
    parser.add_argument("--theme-id", default="", help="theme id, e.g. star-campus")
    parser.add_argument("--display-name", default="", help="visible simulator title")
    parser.add_argument("--institution", default="", help="main institution/place name")
    parser.add_argument(
        "--institution-short", default="", help="short institution name"
    )
    parser.add_argument("--forum-name", default="", help="forum/feed community name")
    parser.add_argument(
        "--messenger-name", default="", help="messenger/private-chat name"
    )
    parser.add_argument(
        "--storage-prefix", default="", help="browser storage key prefix"
    )
    parser.add_argument("--source-theme", default="demo-campus", help="theme to copy")
    parser.add_argument(
        "--core-dependency",
        default=DEFAULT_CORE_DEPENDENCY,
        help="requirements.txt dependency line for esimu-core",
    )
    parser.add_argument(
        "--force", action="store_true", help="allow writing into a non-empty target"
    )
    return parser


def normalize_args(args: argparse.Namespace) -> argparse.Namespace:
    """Fill derived defaults after argparse has parsed user input."""
    args.project_name = args.project_name or args.target.name.replace("-", " ").title()
    args.theme_id = args.theme_id or _slug(args.project_name)
    args.display_name = args.display_name or args.project_name
    args.institution = args.institution or args.display_name
    args.institution_short = args.institution_short or args.institution
    args.forum_name = args.forum_name or f"{args.institution_short}论坛"
    args.messenger_name = args.messenger_name or "校内信"
    args.storage_prefix = args.storage_prefix or _storage_prefix(args.theme_id)
    return args


def main(argv: list[str] | None = None) -> int:
    """CLI entry point."""
    parser = build_parser()
    args = normalize_args(parser.parse_args(argv))
    try:
        target = bootstrap_project(args)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print(f"created esimu project at {target}")
    print(f"theme: {args.theme_id}")
    print(f"next: run esimu validate --root {target} --theme {args.theme_id}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
