"""Generate frontend story metadata from the active theme story file."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from esimu_core.world.story import ThemeStory  # noqa: E402
from esimu_core.world.theme_paths import frontend_story_metadata_output, project_root  # noqa: E402

PROJECT_ROOT = project_root()
OUTPUT_PATH = frontend_story_metadata_output()


def build_typescript() -> str:
    """Render the generated TypeScript story metadata module."""
    metadata_json = json.dumps(
        ThemeStory().public_metadata(),
        ensure_ascii=False,
        indent=2,
    )
    return (
        "// Generated by packages/esimu-core/scripts/sync_story_metadata.py.\n"
        "// Do not edit manually; update themes/<theme_id>/story.json.\n\n"
        f"export const STORY_CONTENT = {metadata_json} as const\n\n"
        "export type PrologueTone = "
        "typeof STORY_CONTENT.prologue.scenes[number]['tone']\n"
    )


def main() -> int:
    """CLI entry point for writing or checking generated story metadata."""
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write generated file")
    mode.add_argument("--check", action="store_true", help="check generated file")
    args = parser.parse_args()

    expected = build_typescript()
    if args.write:
        OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_PATH.write_text(expected, encoding="utf-8")
        print(f"wrote {OUTPUT_PATH.relative_to(PROJECT_ROOT)}")
        return 0

    actual = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
    if actual != expected:
        print(
            f"{OUTPUT_PATH.relative_to(PROJECT_ROOT)} is out of date. "
            "Run: python scripts/sync_story_metadata.py --write",
            file=sys.stderr,
        )
        return 1
    print(f"{OUTPUT_PATH.relative_to(PROJECT_ROOT)} is up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

