"""Generate frontend stat metadata from the active theme's stat definitions.

Copyright (c) 2026 pirate-608. Licensed under the MIT License.
The generated TypeScript file is committed so frontend components can render
stat labels, defaults, ranges, and effect flags without runtime HTTP calls.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = BACKEND_ROOT.parent
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from esimu_core.world.stat_definitions import StatDefinitions  # noqa: E402
from esimu_core.world.theme_paths import frontend_stat_metadata_output, project_root  # noqa: E402

PROJECT_ROOT = project_root()
OUTPUT_PATH = frontend_stat_metadata_output()


def build_typescript() -> str:
    """Render the generated TypeScript stat metadata module."""
    registry = StatDefinitions()
    metadata_json = json.dumps(
        registry.public_metadata()["stats"],
        ensure_ascii=False,
        indent=2,
    )
    return (
        "// Generated by packages/esimu-core/scripts/sync_stat_definitions.py.\n"
        "// Do not edit manually; update the active theme stat_definitions.json.\n\n"
        "export interface StatDefinitionMeta {\n"
        "  id: string\n"
        "  label: string\n"
        "  icon: string\n"
        "  default: number\n"
        "  min: number\n"
        "  max: number\n"
        "  positiveEndpoint: 'max' | 'min' | 'none'\n"
        "  allocatable: boolean\n"
        "  allowItemEffect: boolean\n"
        "  allowEventEffect: boolean\n"
        "  llmContext: boolean\n"
        "  showInCharacterCreate: boolean\n"
        "  showInHud: boolean\n"
        "}\n\n"
        f"export const STAT_INITIAL_BUDGET = {registry.initial_budget}\n\n"
        "export const STAT_DEFINITIONS = "
        f"{metadata_json} as const satisfies readonly StatDefinitionMeta[]\n\n"
        "export const ALLOCATABLE_STATS = STAT_DEFINITIONS.filter(\n"
        "  (stat) => stat.allocatable,\n"
        ")\n\n"
        "export const STAT_META_BY_ID = Object.fromEntries(\n"
        "  STAT_DEFINITIONS.map((stat) => [stat.id, stat]),\n"
        ") as Record<string, StatDefinitionMeta>\n"
    )


def main() -> int:
    """CLI entry point for writing or checking generated stat metadata."""
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write generated file")
    mode.add_argument("--check", action="store_true", help="check generated file")
    args = parser.parse_args()

    expected = build_typescript()
    if args.write:
        OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_PATH.write_text(expected, encoding="utf-8")
        print(f"wrote {OUTPUT_PATH.relative_to(PROJECT_ROOT)}")
        return 0

    actual = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
    if actual != expected:
        print(
            f"{OUTPUT_PATH.relative_to(PROJECT_ROOT)} is out of date. "
            "Run: python scripts/sync_stat_definitions.py --write",
            file=sys.stderr,
        )
        return 1
    print(f"{OUTPUT_PATH.relative_to(PROJECT_ROOT)} is up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

