// Generated by esimu sync.
// Do not edit manually; update themes/<theme_id>/theme.json.

export const THEME_MANIFEST = {
  "schemaVersion": 1,
  "themeId": "zju-simplified",
  "displayName": "ZJUers Simulator Lite",
  "locale": "zh-CN",
  "terms": {
    "institution": "浙江大学",
    "institution_short": "浙大",
    "campus": "求是园",
    "feed": "求是园动态",
    "forum": "CC98",
    "messenger": "钉钉",
    "server": "求是园服务器",
    "player": "学生",
    "player_nickname": "浙大人",
    "semester": "学期",
    "course": "课程",
    "item": "道具",
    "action_gym": "健身",
    "action_game": "打游戏",
    "action_walk": "启真湖散步",
    "action_forum_browse": "刷 CC98",
    "rules": "求是生存手册",
    "notice": "求是园入学须知"
  },
  "storage": {
    "prefix": "esimu_zju_lite"
  },
  "assets": {
    "hero": "assets/campus_gate.webp",
    "logo": "assets/campus_gate.webp"
  }
} as const

export type ThemeTermKey = keyof typeof THEME_MANIFEST.terms
