// Generated by packages/esimu-core/scripts/sync_theme_metadata.py.
// Do not edit manually; update themes/<theme_id>/theme.json.

export const THEME_MANIFEST = {
  "schemaVersion": 1,
  "themeId": "demo-campus",
  "displayName": "Demo Campus Simulator",
  "locale": "zh-CN",
  "terms": {
    "institution": "星桥学院",
    "institution_short": "星桥",
    "campus": "星桥学院",
    "feed": "星桥动态",
    "forum": "星桥论坛",
    "messenger": "校内信",
    "server": "星桥服务器",
    "player": "学生",
    "player_nickname": "星桥学生",
    "semester": "学期",
    "course": "课程",
    "item": "道具",
    "action_gym": "锻炼",
    "action_game": "放松娱乐",
    "action_walk": "校园散步",
    "action_forum_browse": "浏览论坛",
    "rules": "星桥手册",
    "notice": "星桥学院入学须知"
  },
  "storage": {
    "prefix": "esimu_demo"
  },
  "assets": {
    "hero": "assets/hero.webp",
    "logo": "assets/logo.webp"
  }
} as const

export type ThemeTermKey = keyof typeof THEME_MANIFEST.terms
