/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth
         * @description 邀请码认证：验证用户名+邀请码，返回 JWT 和持久凭证
         */
        post: operations["auth_api_auth_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/majors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Majors
         * @description 返回 majors.json 中所有可选专业
         */
        get: operations["get_majors_api_majors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/init_character": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Init Character
         * @description 初始化角色：选择专业并分配初始属性
         */
        post: operations["init_character_api_init_character_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admission_info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Admission Info
         * @description 查询当前用户的用户名和已分配专业
         */
        get: operations["get_admission_info_api_admission_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Game Config
         * @description 获取游戏配置（供前端使用）
         */
        get: operations["get_game_config_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdmissionInfoResponse */
        AdmissionInfoResponse: {
            /** Username */
            username: string;
            /** Assigned Major */
            assigned_major: string;
            /** Token */
            token: string;
        };
        /** AuthRequest */
        AuthRequest: {
            /** Username */
            username: string;
            /** Invite Code */
            invite_code: string;
            /** Token */
            token?: string | null;
        };
        /** AuthResponse */
        AuthResponse: {
            /** Status */
            status: string;
            /** Jwt */
            jwt?: string | null;
            /** User Token */
            user_token?: string | null;
            /** Username */
            username: string;
            /** User Id */
            user_id?: number | null;
            /** Message */
            message?: string | null;
            /** Saves */
            saves?: components["schemas"]["SaveSummary"][];
        };
        /** CourseOption */
        CourseOption: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Credits */
            credits: number;
            /** Difficulty */
            difficulty: number;
        };
        /** GameConfigResponse */
        GameConfigResponse: {
            /** Version */
            version: string;
            semester: components["schemas"]["SemesterConfigResponse"];
            /** Course States */
            course_states: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            /** Cooldowns */
            cooldowns: {
                [key: string]: number;
            };
            /** Tick Interval */
            tick_interval: number;
            /** Base Drain */
            base_drain: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InitCharacterRequest */
        InitCharacterRequest: {
            /** Token */
            token: string;
            /** Major Abbr */
            major_abbr: string;
            /**
             * Iq
             * @default 100
             */
            iq: number;
            /**
             * Eq
             * @default 100
             */
            eq: number;
            /**
             * Luck
             * @default 50
             */
            luck: number;
            /**
             * Charm
             * @default 50
             */
            charm: number;
            /** Stats */
            stats?: {
                [key: string]: number;
            } | null;
        };
        /** InitCharacterResponse */
        InitCharacterResponse: {
            /** Success */
            success: boolean;
            /** Major */
            major: string;
            /** Major Abbr */
            major_abbr: string;
            /** Courses */
            courses: components["schemas"]["CourseOption"][];
        };
        /** MajorOption */
        MajorOption: {
            /** Name */
            name: string;
            /** Abbr */
            abbr: string;
            /** Iq Buff */
            iq_buff: number;
            /** Stress Base */
            stress_base: number;
            /** Desc */
            desc: string;
        };
        /** SaveSummary */
        SaveSummary: {
            /** Save Slot */
            save_slot: number;
            /** Major */
            major: string;
            /** Major Abbr */
            major_abbr: string;
            /** Semester */
            semester: string;
            /** Semester Idx */
            semester_idx: number;
            /** Gpa */
            gpa: string;
            /** Saved At */
            saved_at?: string | null;
            /**
             * Total Play Time
             * @default 0
             */
            total_play_time: number;
        };
        /** SemesterConfigResponse */
        SemesterConfigResponse: {
            /** Durations */
            durations: {
                [key: string]: number;
            };
            /** Default Duration */
            default_duration: number;
            /** Speed Modes */
            speed_modes: {
                [key: string]: number;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_api_auth_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_majors_api_majors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MajorOption"][];
                };
            };
        };
    };
    init_character_api_init_character_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitCharacterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitCharacterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_admission_info_api_admission_info_get: {
        parameters: {
            query?: never;
            header: {
                /** @description Bearer <JWT> */
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdmissionInfoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_config_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameConfigResponse"];
                };
            };
        };
    };
}
